version: '3'
services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: "django_container"
    command: sh ./utils/start.sh
    volumes:
      - "./django:/opt/apps/"
      - "staticdata:/opt/static/"
    expose:
      - 8000
    ports:
      - 8000:8000
    links:
      - db
    tty: true
    stdin_open: true
  nginx:
    image: nginx
    container_name: "nginx_django"
    links:
      - django
    ports:
      - 80:80
    volumes:
      - "./nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/static/"
    tty: true
    stdin_open: true
  db:
    image: postgres
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=pass_dev
      - POSTGRES_DB=develop_db
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    tty: true
    stdin_open: true
volumes:
#  Shared data between django and db
  dbdata:
#  Shared data between django and nginx
  staticdata:
